POST http://localhost:3003/api/cosmetics HTTP/1.1
content-type: application/json

{
    "_id": "xxxxda774913c95013ab4b43",
    "id": 4,
    "name": "Prueba",
    "picture": "pictures/lumene_cc_cream.jpeg",
    "ingredients": [
    {
        "name": "Aqfdsaua"
    },
    {
        "name": "asf"
    },
    {
        "name": "hdfghg"
    }
    ]
}
