POST http://localhost:3001/api/cosmetics HTTP/1.1
content-type: application/json

{
    
    "id": 4,
    "name": "Prueba",
    "picture": "pictures/lumene_cc_cream.jpeg",
    "ingredients": [
    {
        "name": "Aqfdsaua"
    },
    {
        "name": "asf"
    },
    {
        "name": "hdfghg"
    }
    ]
}
